
CC = g++
LINK = ar

INCS += -I ./inc -I $(SDL)/Headers/

BIN = ./bin
SRC = ./src

OUTPUT = GKit.lib

CC_OPTIONS = -std=c++17 -g -Wall -Werror

OBJECTS = $(patsubst $(SRC)/%.cpp, $(BIN)/%.o, $(wildcard $(SRC)/*.cpp))

$(BIN)/%.o: $(SRC)/%.cpp
	$(CC) $(CC_OPTIONS) $(INCS) -c $^ -o $@

$(BIN)/$(OUTPUT): $(OBJECTS)
	$(LINK) rcs $@ $^

.PHONY: clean
clean:
	rm -f $(BIN)/*.o
	rm -f $(BIN)/$(OUTPUT)
